"""Add explicit lengths to String columns for MySQL

Revision ID: 3f66284b162f
Revises: 
Create Date: 2025-07-24 13:39:00.461797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f66284b162f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('discovered_from', sa.String(length=255), nullable=False),
    sa.Column('search_query_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_status', sa.String(length=32), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_query.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_url_crawl_status'), 'url', ['crawl_status'], unique=False)
    op.create_index(op.f('ix_url_domain'), 'url', ['domain'], unique=False)
    op.create_index(op.f('ix_url_id'), 'url', ['id'], unique=False)
    op.create_table('crawled_content',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('raw_html_path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawled_content_id'), 'crawled_content', ['id'], unique=False)
    op.create_table('extracted_lead',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('lead_type', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['crawled_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_lead_email'), 'extracted_lead', ['email'], unique=False)
    op.create_index(op.f('ix_extracted_lead_id'), 'extracted_lead', ['id'], unique=False)
    op.create_table('lead_score',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('scoring_factors', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['extracted_lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_score_id'), 'lead_score', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_score_id'), table_name='lead_score')
    op.drop_table('lead_score')
    op.drop_index(op.f('ix_extracted_lead_id'), table_name='extracted_lead')
    op.drop_index(op.f('ix_extracted_lead_email'), table_name='extracted_lead')
    op.drop_table('extracted_lead')
    op.drop_index(op.f('ix_crawled_content_id'), table_name='crawled_content')
    op.drop_table('crawled_content')
    op.drop_index(op.f('ix_url_id'), table_name='url')
    op.drop_index(op.f('ix_url_domain'), table_name='url')
    op.drop_index(op.f('ix_url_crawl_status'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
